In [50]:
import pandas as pd

df=pd.read_csv('../app/data/jobs.csv')

df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [51]:
features = ["Job Title", "Job Description"]

for feature in features:
    df[feature] = df[feature].str.lower()

In [52]:
import pandas as pd
import re  

def parse_salary(salary):
    # Supprimer tout sauf chiffres, tiret et point
    salary = re.sub(r'[^\d\-.]', '', salary)
    
    if '-' in salary:
        low, high = salary.split('-')
        return (float(low.strip()) + float(high.strip())) / 2
    else:
        return float(salary.strip())

# Appliquer à toute la colonne
df['Salary_Estimate'] = df['Salary Estimate'].apply(parse_salary)
print(df[['Salary_Estimate']])

     Salary_Estimate
0              154.0
1              154.0
2              154.0
3              154.0
4              154.0
..               ...
667            136.0
668            136.0
669            136.0
670            136.0
671            136.0

[672 rows x 1 columns]

In [53]:
from sklearn.preprocessing import OrdinalEncoder

most_freq = df['Revenue'].value_counts()

second_most_freq = most_freq.index[1]

df['Revenue'] = df['Revenue'].replace({
    "Unknown / Non-Applicable": second_most_freq,
    '-1' :second_most_freq
})


revenue= [
'Less than $1 million (USD)'    ,
'$1 to $5 million (USD)'          ,
'$5 to $10 million (USD)'     ,
'$10 to $25 million (USD)'     ,
'$25 to $50 million (USD)'   ,
'$50 to $100 million (USD)'         ,
'$100 to $500 million (USD)'     ,
'$500 million to $1 billion (USD)' ,
'$1 to $2 billion (USD)'    ,
'$2 to $5 billion (USD)'        ,
'$5 to $10 billion (USD)'     ,
'$10+ billion (USD)'              ,
]

encoder=OrdinalEncoder(categories=[revenue])

df['Revenue']=encoder.fit_transform(df[['Revenue']])
print(df['Revenue'])

0      6.0
1      8.0
2      6.0
3      6.0
4      6.0
      ...
667    6.0
668    6.0
669    6.0
670    1.0
671    8.0
Name: Revenue, Length: 672, dtype: float64

In [54]:
most_freq = df['Size'].mode()[0]

df['Size'] = df['Size'].replace(["Unknown", "-1"], most_freq)


from sklearn.preprocessing import OrdinalEncoder

size= [
'1 to 50 employees'  ,
'51 to 200 employees',
'201 to 500 employees'  ,
'501 to 1000 employees' ,
'1001 to 5000 employees' ,
'5001 to 10000 employees',
'10000+ employees',
]

encoder=OrdinalEncoder(categories=[size])

df['Size']=encoder.fit_transform(df[['Size']])
print(df['Size'])

0      4.0
1      5.0
2      4.0
3      3.0
4      1.0
      ...
667    4.0
668    1.0
669    1.0
670    0.0
671    4.0
Name: Size, Length: 672, dtype: float64

In [55]:
from sklearn.preprocessing import LabelEncoder

lencoder=LabelEncoder()
df['Location']=lencoder.fit_transform(df['Location'])
df['Company_Name']=lencoder.fit_transform(df['Company Name'])

In [56]:
most_freq=df["Type of ownership"].value_counts().idxmax()

df['Type of ownership'] = df['Type of ownership'].replace({
   "Unknown": most_freq,
   "-1":most_freq
})

In [57]:
df['Type_ownership']=lencoder.fit_transform(df['Type of ownership'])

In [58]:
most_freq = df['Industry'].value_counts()
second_most_freq = most_freq.index[1]

df['Industry']=lencoder.fit_transform(df['Industry'])

In [59]:

df["Sector"].value_counts()
most_freq=df["Sector"].value_counts().idxmax()

df['Sector'].replace({
   "Unknown": most_freq,
   "-1":most_freq
})

df['Sector']=lencoder.fit_transform(df['Sector'])

In [60]:
df['Competitors'] = df['Competitors'].apply(lambda x: 0 if x == '-1' else 1)

In [61]:
df['Job_Title']=df['Job Title']
df['Job_Description']=df['Job Description']

In [62]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership,Job_Title,Job_Description
0,0,sr data scientist,$137K-$171K (Glassdoor est.),description\n\nthe senior data scientist is re...,3.1,Healthfirst\n3.1,119,"New York, NY",4.0,1993,Nonprofit Organization,31,13,6.0,1,154.0,175,6,sr data scientist,description\n\nthe senior data scientist is re...
1,1,data scientist,$137K-$171K (Glassdoor est.),"secure our nation, ignite your future\n\njoin ...",4.2,ManTech\n4.2,35,"Herndon, VA",5.0,1968,Company - Public,43,5,8.0,0,154.0,236,2,data scientist,"secure our nation, ignite your future\n\njoin ..."
2,2,data scientist,$137K-$171K (Glassdoor est.),overview\n\n\nanalysis group is one of the lar...,3.8,Analysis Group\n3.8,19,"Boston, MA",4.0,1981,Private Practice / Firm,12,5,6.0,0,154.0,31,8,data scientist,overview\n\n\nanalysis group is one of the lar...
3,3,data scientist,$137K-$171K (Glassdoor est.),job description:\n\ndo you have a passion for ...,3.5,INFICON\n3.5,120,"Bad Ragaz, Switzerland",3.0,2000,Company - Public,16,14,6.0,1,154.0,186,2,data scientist,job description:\n\ndo you have a passion for ...
4,4,data scientist,$137K-$171K (Glassdoor est.),data scientist\naffinity solutions / marketing...,2.9,Affinity Solutions\n2.9,119,"New York, NY",1.0,1998,Company - Private,2,5,6.0,1,154.0,18,1,data scientist,data scientist\naffinity solutions / marketing...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,data scientist,$105K-$167K (Glassdoor est.),summary\n\nwe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,61,"Fort Lee, NJ",4.0,1989,Company - Private,2,5,6.0,0,136.0,373,1,data scientist,summary\n\nwe’re looking for a data scientist ...
668,668,data scientist,$105K-$167K (Glassdoor est.),job description\nbecome a thought leader withi...,-1.0,JKGT,162,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,203,1,data scientist,job description\nbecome a thought leader withi...
669,669,data scientist,$105K-$167K (Glassdoor est.),join a thriving company that is changing the w...,-1.0,AccessHope,86,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,11,1,data scientist,join a thriving company that is changing the w...
670,670,data scientist,$105K-$167K (Glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,ChaTeck Incorporated\n5.0,162,"Santa Clara, CA",0.0,-1,Company - Private,2,5,1.0,0,136.0,83,1,data scientist,100 remote opportunity as an ainlp data scient...
671,671,data scientist,$105K-$167K (Glassdoor est.),description\n\nthe data scientist will be part...,2.7,1-800-Flowers\n2.7,119,"Carle Place, NY",4.0,1976,Company - Public,57,5,8.0,0,136.0,0,2,data scientist,description\n\nthe data scientist will be part...

In [63]:
import re

def clean_text(text):
    # Convert to string (in case of NaN)
    text = str(text)
    
    # Lowercase
    text = text.lower()
    
    # Remove \n and extra spaces
    text = re.sub(r'\n+', ' ', text)
    
    # Remove special characters (keep letters and numbers)
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

df['Job_Description'] = df['Job_Description'].apply(clean_text)

In [64]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership,Job_Title,Job_Description
0,0,sr data scientist,$137K-$171K (Glassdoor est.),description\n\nthe senior data scientist is re...,3.1,Healthfirst\n3.1,119,"New York, NY",4.0,1993,Nonprofit Organization,31,13,6.0,1,154.0,175,6,sr data scientist,description the senior data scientist is respo...
1,1,data scientist,$137K-$171K (Glassdoor est.),"secure our nation, ignite your future\n\njoin ...",4.2,ManTech\n4.2,35,"Herndon, VA",5.0,1968,Company - Public,43,5,8.0,0,154.0,236,2,data scientist,secure our nation ignite your future join the ...
2,2,data scientist,$137K-$171K (Glassdoor est.),overview\n\n\nanalysis group is one of the lar...,3.8,Analysis Group\n3.8,19,"Boston, MA",4.0,1981,Private Practice / Firm,12,5,6.0,0,154.0,31,8,data scientist,overview analysis group is one of the largest ...
3,3,data scientist,$137K-$171K (Glassdoor est.),job description:\n\ndo you have a passion for ...,3.5,INFICON\n3.5,120,"Bad Ragaz, Switzerland",3.0,2000,Company - Public,16,14,6.0,1,154.0,186,2,data scientist,job description do you have a passion for data...
4,4,data scientist,$137K-$171K (Glassdoor est.),data scientist\naffinity solutions / marketing...,2.9,Affinity Solutions\n2.9,119,"New York, NY",1.0,1998,Company - Private,2,5,6.0,1,154.0,18,1,data scientist,data scientist affinity solutions marketing cl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,data scientist,$105K-$167K (Glassdoor est.),summary\n\nwe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,61,"Fort Lee, NJ",4.0,1989,Company - Private,2,5,6.0,0,136.0,373,1,data scientist,summary we re looking for a data scientist to ...
668,668,data scientist,$105K-$167K (Glassdoor est.),job description\nbecome a thought leader withi...,-1.0,JKGT,162,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,203,1,data scientist,job description become a thought leader within...
669,669,data scientist,$105K-$167K (Glassdoor est.),join a thriving company that is changing the w...,-1.0,AccessHope,86,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,11,1,data scientist,join a thriving company that is changing the w...
670,670,data scientist,$105K-$167K (Glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,ChaTeck Incorporated\n5.0,162,"Santa Clara, CA",0.0,-1,Company - Private,2,5,1.0,0,136.0,83,1,data scientist,100 remote opportunity as an ainlp data scient...
671,671,data scientist,$105K-$167K (Glassdoor est.),description\n\nthe data scientist will be part...,2.7,1-800-Flowers\n2.7,119,"Carle Place, NY",4.0,1976,Company - Public,57,5,8.0,0,136.0,0,2,data scientist,description the data scientist will be part of...

In [65]:
# import nltk
# from nltk.corpus import stopwords

# # Download stopwords if not already
# # nltk.download('stopwords')

# stop_words = set(stopwords.words('english'))

# # Apply stopword removal to each job description
# df['Job_Description'] = df['Job_Description'].apply(lambda x: ' '.join(
#     word for word in x.lower().replace('\n', ' ').split() if word not in stop_words
# ))

In [66]:
df

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership,Job_Title,Job_Description
0,0,sr data scientist,$137K-$171K (Glassdoor est.),description\n\nthe senior data scientist is re...,3.1,Healthfirst\n3.1,119,"New York, NY",4.0,1993,Nonprofit Organization,31,13,6.0,1,154.0,175,6,sr data scientist,description the senior data scientist is respo...
1,1,data scientist,$137K-$171K (Glassdoor est.),"secure our nation, ignite your future\n\njoin ...",4.2,ManTech\n4.2,35,"Herndon, VA",5.0,1968,Company - Public,43,5,8.0,0,154.0,236,2,data scientist,secure our nation ignite your future join the ...
2,2,data scientist,$137K-$171K (Glassdoor est.),overview\n\n\nanalysis group is one of the lar...,3.8,Analysis Group\n3.8,19,"Boston, MA",4.0,1981,Private Practice / Firm,12,5,6.0,0,154.0,31,8,data scientist,overview analysis group is one of the largest ...
3,3,data scientist,$137K-$171K (Glassdoor est.),job description:\n\ndo you have a passion for ...,3.5,INFICON\n3.5,120,"Bad Ragaz, Switzerland",3.0,2000,Company - Public,16,14,6.0,1,154.0,186,2,data scientist,job description do you have a passion for data...
4,4,data scientist,$137K-$171K (Glassdoor est.),data scientist\naffinity solutions / marketing...,2.9,Affinity Solutions\n2.9,119,"New York, NY",1.0,1998,Company - Private,2,5,6.0,1,154.0,18,1,data scientist,data scientist affinity solutions marketing cl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,data scientist,$105K-$167K (Glassdoor est.),summary\n\nwe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,61,"Fort Lee, NJ",4.0,1989,Company - Private,2,5,6.0,0,136.0,373,1,data scientist,summary we re looking for a data scientist to ...
668,668,data scientist,$105K-$167K (Glassdoor est.),job description\nbecome a thought leader withi...,-1.0,JKGT,162,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,203,1,data scientist,job description become a thought leader within...
669,669,data scientist,$105K-$167K (Glassdoor est.),join a thriving company that is changing the w...,-1.0,AccessHope,86,-1,1.0,-1,Company - Private,0,0,6.0,0,136.0,11,1,data scientist,join a thriving company that is changing the w...
670,670,data scientist,$105K-$167K (Glassdoor est.),100 remote opportunity as an ainlp data scient...,5.0,ChaTeck Incorporated\n5.0,162,"Santa Clara, CA",0.0,-1,Company - Private,2,5,1.0,0,136.0,83,1,data scientist,100 remote opportunity as an ainlp data scient...
671,671,data scientist,$105K-$167K (Glassdoor est.),description\n\nthe data scientist will be part...,2.7,1-800-Flowers\n2.7,119,"Carle Place, NY",4.0,1976,Company - Public,57,5,8.0,0,136.0,0,2,data scientist,description the data scientist will be part of...

In [67]:
df['Job_Description'] = (
    df['Job_Description']
    .str.strip()
    .str.replace(r'Description\n\n', '', regex=True)  # ← spécifique à ton CSV
    .str.replace(r'•', '', regex=True)
    .str.replace(r'\n', ' ', regex=True)
    .str.replace(r'\t', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
)

In [68]:
df=df.drop(columns=["Headquarters","Salary Estimate","Company Name","Type of ownership"])

# cols=['Headquarters','Job_Description']

# df=df.drop(columns=cols)

In [69]:
data=df.to_csv('clean_jobs2.csv',index=False)

In [70]:
import pandas as pd

data=pd.read_csv('clean_jobs2.csv')

data.head()

,index,Job Title,Job Description,Rating,Location,Size,Founded,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership,Job_Title,Job_Description
0,0,sr data scientist,description\n\nthe senior data scientist is re...,3.1,119,4.0,1993,31,13,6.0,1,154.0,175,6,sr data scientist,description the senior data scientist is respo...
1,1,data scientist,"secure our nation, ignite your future\n\njoin ...",4.2,35,5.0,1968,43,5,8.0,0,154.0,236,2,data scientist,secure our nation ignite your future join the ...
2,2,data scientist,overview\n\n\nanalysis group is one of the lar...,3.8,19,4.0,1981,12,5,6.0,0,154.0,31,8,data scientist,overview analysis group is one of the largest ...
3,3,data scientist,job description:\n\ndo you have a passion for ...,3.5,120,3.0,2000,16,14,6.0,1,154.0,186,2,data scientist,job description do you have a passion for data...
4,4,data scientist,data scientist\naffinity solutions / marketing...,2.9,119,1.0,1998,2,5,6.0,1,154.0,18,1,data scientist,data scientist affinity solutions marketing cl...

In [71]:
data

,index,Job Title,Job Description,Rating,Location,Size,Founded,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership,Job_Title,Job_Description
0,0,sr data scientist,description\n\nthe senior data scientist is re...,3.1,119,4.0,1993,31,13,6.0,1,154.0,175,6,sr data scientist,description the senior data scientist is respo...
1,1,data scientist,"secure our nation, ignite your future\n\njoin ...",4.2,35,5.0,1968,43,5,8.0,0,154.0,236,2,data scientist,secure our nation ignite your future join the ...
2,2,data scientist,overview\n\n\nanalysis group is one of the lar...,3.8,19,4.0,1981,12,5,6.0,0,154.0,31,8,data scientist,overview analysis group is one of the largest ...
3,3,data scientist,job description:\n\ndo you have a passion for ...,3.5,120,3.0,2000,16,14,6.0,1,154.0,186,2,data scientist,job description do you have a passion for data...
4,4,data scientist,data scientist\naffinity solutions / marketing...,2.9,119,1.0,1998,2,5,6.0,1,154.0,18,1,data scientist,data scientist affinity solutions marketing cl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,667,data scientist,summary\n\nwe’re looking for a data scientist ...,3.6,61,4.0,1989,2,5,6.0,0,136.0,373,1,data scientist,summary we re looking for a data scientist to ...
668,668,data scientist,job description\nbecome a thought leader withi...,-1.0,162,1.0,-1,0,0,6.0,0,136.0,203,1,data scientist,job description become a thought leader within...
669,669,data scientist,join a thriving company that is changing the w...,-1.0,86,1.0,-1,0,0,6.0,0,136.0,11,1,data scientist,join a thriving company that is changing the w...
670,670,data scientist,100 remote opportunity as an ainlp data scient...,5.0,162,0.0,-1,2,5,1.0,0,136.0,83,1,data scientist,100 remote opportunity as an ainlp data scient...
671,671,data scientist,description\n\nthe data scientist will be part...,2.7,119,4.0,1976,57,5,8.0,0,136.0,0,2,data scientist,description the data scientist will be part of...

In [72]:
data=data.drop(columns=["Job Title"	,"index","Job Description","Job_Title","Job_Description"])

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


X = data.drop(columns=['Salary_Estimate'])
y = data['Salary_Estimate']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# preprocessor = ColumnTransformer(
#     transformers=[
#         ('title_tfidf', TfidfVectorizer(max_features=1000), 'Job Title'),
#         ('desc_tfidf', TfidfVectorizer(max_features=5000), 'Job_Description')
#     ],
#     remainder='drop'   
# )

model = Pipeline([
    # ('preprocessing', preprocessor),
    ('regressor', RandomForestRegressor())
])
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MSE: 1311.289988507663
R2: -0.12453237236467807

In [74]:
data

,Rating,Location,Size,Founded,Industry,Sector,Revenue,Competitors,Salary_Estimate,Company_Name,Type_ownership
0,3.1,119,4.0,1993,31,13,6.0,1,154.0,175,6
1,4.2,35,5.0,1968,43,5,8.0,0,154.0,236,2
2,3.8,19,4.0,1981,12,5,6.0,0,154.0,31,8
3,3.5,120,3.0,2000,16,14,6.0,1,154.0,186,2
4,2.9,119,1.0,1998,2,5,6.0,1,154.0,18,1
...,...,...,...,...,...,...,...,...,...,...,...
667,3.6,61,4.0,1989,2,5,6.0,0,136.0,373,1
668,-1.0,162,1.0,-1,0,0,6.0,0,136.0,203,1
669,-1.0,86,1.0,-1,0,0,6.0,0,136.0,11,1
670,5.0,162,0.0,-1,2,5,1.0,0,136.0,83,1
671,2.7,119,4.0,1976,57,5,8.0,0,136.0,0,2

In [75]:
import joblib
joblib.dump(model, './modelrf.pkl')

['./modelrf.pkl']